# Generated by Django 2.2 on 2019-05-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('addedBy', models.CharField(max_length=255, verbose_name='Added by')),
                ('nextParty', models.CharField(max_length=255, verbose_name='Logo')),
                ('transType', models.CharField(max_length=255, verbose_name='Type')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
    ]
